apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secubank-online-boutique-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ycseo-git/secubank-gitops.git
    targetRevision: main
    path: apps/secubank/online-boutique/dev/chart
    helm:
      valueFiles:
        - values.yaml
        - values-images.yaml
        - values-security.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: secubank-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
